config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs
  resources :subads, :path => 'announcements'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscriptions, :path => 'pets' 
  root 'home#index'
  mount Thredded::Engine => '/forum'
  resource :messageboard, path: 'messageboards', only: [:new]
  get '/private-topics/new' => 'thredded/private_topics#new', :as => :new_private_topic
  
  
  devise_for :users, 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'edit'}, 
  :controllers => { 
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"}

  get 'users/:id' => 'users#show', :as => :user_profile
  get 'persons/:id/profile' => 'persons#show', :as => :persons_profile
  get 'home/about', :path => 'about'
  get 'home/donate', :path => 'donate'
  get 'home/faq', :path => 'faq'
  get 'subscriptions/:id/lost' => "subscriptions#lost", :as => :subscriptions_lost
  get 'subscriptions/:id/found' => "subscriptions#found", :as => :subscriptions_found
  get 'subscriptions/lost_pets' => "subscriptions#lost_pets", :as => :lost_pets, :path => 'lost/pets'

  get 'persons/edit'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
         
  devise :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :subscriptions
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.image = auth.info.image
      user.location = auth.info.location
      user.password = Devise.friendly_token[0,20]
    end      
  end
  
  def to_param
    "#{id} #{name}".parameterize
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook 
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to edit_user_registration_url
    end
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
def show
    @subads = Subad.all
    @subscriptions = Subscription.all.paginate(:page => params[:page], :per_page => 3)
    @user = User.find(params[:id])
end



end

app/views/users/_sidebar1.html.erb
  <%= render 'sidebar' %>

app/views/users/_subscriptions.html.erb
<style>
.box{
margin-top: 20%;
}

a {
color: #9c27b0;
font-size: 14px;
text-transform: uppercase;
}

a:hover {
color: #983a79 !important;
}

.avatar{
box-shadow:none;
}

.bold{
font-weight:600;
}

</style>


<% @user.subscriptions.each do |subscription| %>
<div class="box">
<div class="avatar">
<!--needs to be refactored-->
<% if subscription.company == "Hulu" %>
<img style= "margin-top: 50%; opacity: 0.6;" src="https://www.hulu.com/press/wp-content/uploads/2016/10/hulu-interactive-rgb-1.png">
<% elsif subscription.company == "Netflix" %>
<img style= "margin-top: 50%; opacity: 0.6;" src="http://www.stickpng.com/assets/images/580b57fcd9996e24bc43c529.png">
<% elsif subscription.company == "Spotify" %>
<img style="border-radius: 0px; margin-top: 30%; opacity: 0.6; margin-left: 35px; width: 30%" src="https://images.vexels.com/media/users/3/137413/isolated/preview/4acb8e52632aa9b7c874b878eaf02bc4-spotify-icon-logo-by-vexels.png">
<% elsif subscription.company == "Xbox" %>
<img style="border-radius: 0px; margin-top: 35%; margin-left: 42px; width: 25%; opacity:0.6" src="http://diylogodesigns.com/blog/wp-content/uploads/2016/06/Xbox-360-logo-icon-png.png">
<% elsif subscription.company == "Itunes" %>
<img style="border-radius: 0px; margin-top: 45%; opacity: 0.6; margin-left: -10px;" src="https://planetared.com/wp-content/uploads/2017/03/itunes.png">
<% elsif subscription.company == "Microsoft" %>
<img style="border-radius: 0px; margin-top: 25%; margin-left: 20px; width: 50%" src="http://diylogodesigns.com/blog/wp-content/uploads/2016/04/Microsoft-Logo-icon-png-Transparent-Background.png">
<% elsif subscription.company == "SoundCloud" %>
<img style="margin-top: 25%; width: 50%; margin-left: 7%; opacity: 0.6;" src="http://assets.stickpng.com/thumbs/580b57fcd9996e24bc43c537.png">
<% elsif subscription.company == "HBO" %>
<img style="border-radius: 0px; opacity: 0.6; margin-top: 60%; margin-left: 30" src="https://vignette3.wikia.nocookie.net/logopedia/images/d/d6/HBO_logo_blue.svg/revision/latest/scale-to-width-down/497?cb=20150301002247">
<% elsif subscription.company == "TNT" %>
<img style="border-radius: 0px; margin-top: 30%; opacity: 0.6; margin-left: 30px; width: 30%" src="https://upload.wikimedia.org/wikipedia/en/thumb/e/ec/TNT_(TV_Channel).svg/1200px-TNT_(TV_Channel).svg.png">
<% elsif subscription.company == "Amazon" %>
<img style="border-radius: 0px; margin-top: 30%; opacity: 0.6; margin-left: 40px; width: 30%" src="http://www.freelogovectors.net/wp-content/uploads/2016/12/amazon_logo.png">
<% else %>

<% end %>
</div>
<div class="box-inner">


<h3 class="name bold"><%= link_to subscription.title, subscription %></h3>
<h4 class="occupation"> </h4>
<% if current_user %>
<!--edit links-->
<p class="location">
<%= link_to edit_subscription_path(subscription) do %>
<i class="fa fa-pencil fa-fw action-icons" data-toggle="tooltip" data-placement="right" title="Edit"></i>
<% end %>

<%= link_to subscription, method: :delete, data: { confirm: 'Are you sure?' } do %>
<i class="fa fa-ban fa-fw action-icons" data-toggle="tooltip" data-placement="right" title="Delete"></i>
<% end %>
</p>
<!--end-->
<% end %>
<% if subscription.url.blank? %>

<% else %>
<h3 class="followers-title"><%= link_to 'Subcription Profile', subscription.url, target: "_blank" %>
</h3>
<% end %>

</div>
</div>
<br>
<br>
<% end %>

<!--will_paginate @subscriptions %>-->

app/views/users/show.html.1.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300);
@import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100);
body,
html,
.wrapper {
  height: auto;
  width: 100%;
}

/*.avatar{*/
/*margin-top: 20%;*/
}

body {
  font-family: 'Open Sans', sans-serif;
  color: #404040;
}
.wrapper {
  background:linear-gbodyradient(to left,#7b4397,#dc2430);
  position: relative;
  z-index: 1;
}

.fa-plus{
color: #be2e50;
}

.wrapper:before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  /*background-image: url("http://remtsoy.com/experiments/user_card/img/food.png");*/
  z-index: 2;
  opacity: 0.3;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
  filter: alpha(opacity=30);
}
.wrapper-inner {
  position: relative;
  z-index: 3;
  height: 100%;
  margin-top: 45%;
}
.box-wrapper {
  position: absolute;
  top: 10%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  -o-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  margin-top: 40px;
  z-index: 1;
}
.box {
  position: relative;
  -webkit-border-radius: 8px;
  border-radius: 8px;
  -webkit-box-shadow: 0 4px 1px rgba(0,0,0,0.1);
  box-shadow: 0 4px 1px rgba(0,0,0,0.1);
  width: 380px;
  background: #fff;
  text-align: center;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding-top: 65px;
  margin-top:100%;
}
.box-inner {
  padding: 30px;
}
.avatar {
  -webkit-border-radius: 50%;
  border-radius: 50%;
  -webkit-box-shadow: 0 0 0 3px #c30eb8 , 0 0 0 8px #fff;
  box-shadow: 0 0 0 3px #c30eb8 , 0 0 0 8px #fff;
  top: -75px;
  margin-left: -75px;
  left: 50%;
  position: absolute;
}
.avatar img {
  width: 150px;
  -webkit-border-radius: 50%;
  border-radius: 50%;
  display: block;
}
h1,
h2,
h3,
h4,
h5 {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  margin-top: 0;
  margin-bottom: 15px;
}
.name,
.followers-title {
  font-size: 38px;
  font-weight: 100;
  font-family: 'Roboto', sans-serif;
  margin-bottom: 2px;
  color: #3a3a3a;
}
.occupation {
  font-size: 18px;
  font-style: italic;
  color: #707070;
  margin-bottom: 2px;
}
.location {
  color: #b3b3b3;
  font-size: 14px;
  margin-top: 5px;
  margin-bottom: 15px;
  padding-bottom: 15px;
  border-bottom: 1px solid #f2f2f2;
}
.location .fa {
  color: #c6c6c6;
  margin-right: 4px;
}
.followers-title {
  font-size: 30px;
  color: #666;
  margin-bottom: 5px;
}
.followers-list {
  list-style: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  padding-bottom: 5px;
  display: table;
  margin: 0 auto;
}
.followers-list > li {
  display: block;
  float: left;
  margin: 0 5px;
}
.followers-list > li a {
  display: block;
  -webkit-border-radius: 50%;
  border-radius: 50%;
  -webkit-transition: 0.3s;
  -moz-transition: 0.3s;
  -o-transition: 0.3s;
  -ms-transition: 0.3s;
  transition: 0.3s;
  height: 45px;
  width: 45px;
  text-decoration: none;
}
.followers-list > li a img {
  -webkit-border-radius: 50%;
  border-radius: 50%;
  width: 45px;
  display: block;
  -webkit-transition: 0.3s;
  -moz-transition: 0.3s;
  -o-transition: 0.3s;
  -ms-transition: 0.3s;
  transition: 0.3s;
  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  -ms-backface-visibility: hidden;
  backface-visibility: hidden;
  height: 45px;
}
.followers-list > li a:hover img {
  opacity: 0.8;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
  filter: alpha(opacity=80);
}
.followers-list > li.follow-list-item a {
  background: #4d4d4d;
  color: #fff;
}
.followers-list > li.follow-list-item a:hover {
  background: #c30eb8;
}
.followers-list > li.follow-list-item .fa-plus {
  display: block;
  height: 45px;
  width: 45px;
  line-height: 45px;
}
.social-list {
  list-style: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  padding-top: 1px;
  display: table;
  margin: 0 auto;
}
.social-list > li {
  float: left;
  display: block;
}
.social-list > li > a {
  display: block;
  width: 45px;
  height: 55px;
  line-height: 55px;
  font-size: 28px;
  text-decoration: none;
  color: #b3b3b3;
  border-right: 1px solid #ededed;
  -webkit-transition: 0.2s;
  -moz-transition: 0.2s;
  -o-transition: 0.2s;
  -ms-transition: 0.2s;
  transition: 0.2s;
}
.social-list > li > a:hover {
  background: #c30eb8;
  color: #fff;
}
.social-list > li > a:hover.fa-facebook {
  background: #3b5998;
}
.social-list > li > a:hover.fa-dribbble {
  background: #c32361;
}
.social-list > li > a:hover.fa-twitter {
  background: #55acee;
}
.social-list > li > a:hover.fa-pinterest {
  background: #cd2129;
}
.social-list > li > a:hover.fa-linkedin {
  background: #1683bc;
}
.social-list > li:last-child > a {
  border-right: none;
}
/* iphone 6 Portrait */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait) { 
.wrapper-inner {
  margin-top:190%;
  }
}

/* Ipad Landscape */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation:landscape) {
.wrapper-inner{
  margin-top: 70%;
}
}
/* Ipad Portrait */
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation:portrait) {
.wrapper-inner{
  margin-top: 100%;
}
}
</style>

<div class="wrapper">
<div class="wrapper-inner">
<div class="box-wrapper">
<div class="box" style="padding-bottom: 30px;">
<div class="avatar">
<%= image_tag current_person.image %>
</div>
<div class="box-inner">
<h3 class="name"><%= current_person.name %></h3>
<h4 class="occupation"> </h4>
<p class="location"><i class="fa fa-amazon"></i> <i class="fa fa-apple"></i> <i class="fa fa-paypal"></i> <i class="fa fa-spotify"></i> <i class="fa fa-youtube"></i> <i class="fa fa-steam"></i> </p>
<h3 class="followers-title"><%= @person.subscriptions.count %> Total Subscriptions</h3>

</div>
<ul class="social-list">

<%= link_to new_subscription_path do %>
<li class="fa fa-plus" data-placement="right" data-toggle="tooltip" title="New Subcription"></li>
<% end %>

</ul>
</div>
<%= render 'subscriptions' %>
</div>

</div>
</div>

<!-- tooltips -->
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8" />
<!--bootstrap-->
 
<title><%= @user.name %> | Profile</title>
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
<!-- CSS Files -->
<style>
.litter-box-row{
margin-left: 33%;
}

.btn-primary{
background-color: rgb(86, 184, 143);
border-color: transparent;
}
.btn-primary:hover {
color: #ffffff !important;
background-color: rgb(86, 184, 143);
border-color: transparent;
}
#report_found{
margin-top: -40%;
}
.alert-notice {
z-index: 1031;
}
.btn-xl{
margin-top: -30%;
position: absolute;
margin-left: 20%;
}
.thredded--navigation--search{
margin-left: -10% !important;
}
.fa-pencil{
/*margin-left: 48%;*/
font-size: 8px;
/*color: #e6d5ba;*/
}
.bg-primary {
background-color: rgba(207, 216, 220, 0.38) !important;
}
/* iphone 6 Portrait */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
#timeline {
width:auto;
  }
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
#report_found{
margin-left: -40%;
  }
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
#report_lost{
margin-left: -40%;
  }
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
.wrapper{
overflow-x:hidden;
  }
}
/*@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){*/
/*body{*/
/*overflow-x:hidden;*/
/*  }*/
/*}*/
</style>
</head>

<body class="profile-page">

<div class="wrapper">
<div class="page-header page-header-small" filter-color="orange">
<div class="page-header-image" data-parallax="true" style="background-image: url('');">
</div>
<div class="container">
<div class="content-center">
<div class="photo-container">
<%= image_tag(@user.image) %>
</div>
<h3 class="title"><%= @user.name %></h3>
<br>
<p class="category"> </p>
<div class="content">
<div class="social-description">
<!--<h2>1 New</h2>-->
<!--<p>Messages</p>-->
</div>
<!--<div class="social-description">-->
<!--    <h2>26</h2>-->
<!--    <p>Comments</p>-->
<!--</div>-->
<!--<div class="social-description">-->
<!--    <h2>48</h2>-->
<!--    <p>Bookmarks</p>-->
<!--</div>-->
</div>
</div>
</div>
</div>
<div class="section">
<div class="container">
<div class="button-container">
<%= link_to 'Message', new_private_topic_path,  target: "_blank", class: "btn btn-primary btn-round btn-lg", 'data-toggle' => 'tooltip', 'data-placement' => 'top', :title => 'Did you locate a lost pet? Send the owner a private message.' %>
<!--<a href="#button" class="btn btn-default btn-round btn-lg btn-icon" rel="tooltip" title="Did you located a lost pet? Place a call to the owner.">-->
<!--check if phone number is blank-->
<% if @user.phone_number.blank? %>

<% else %>
<%= link_to "tel:#{@user.phone_number}", class: "btn btn-default btn-lg btn-icon", 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => 'Did you locate a lost pet? Place a call to the owner.' do %>
<i class="fa fa-phone"></i>
 <% end %>
<% end %>
</a>
<% if @user.facebook.blank? %>

<% else %>
<%= link_to @user.facebook, target: "_blank", class: "btn btn-default btn-lg btn-icon" do %>
<i class="fa fa-facebook"></i>
<% end %>
<% end %>
</div>
<h3 class="title"> </h3>

<h5 class="description"><%= @user.about %></h5>

<div class="row litter-box-row">
<div class="col-md-6 offset-md-3">
<h4 class="title text-center">Litter Box</h4>
<div class="nav-align-center">
<ul class="nav nav-pills nav-pills-primary" role="tablist">
<li class="nav-item">
<a class="nav-link" data-toggle="tab" href="#profile" role="tablist">
<i class="fa fa-paw" aria-hidden="true" rel="tooltip" data-placement="right" title="The Pets in my household"></i>
</a>
</li>
<li class="nav-item">
<a class="nav-link active" data-toggle="tab" href="#home" role="tablist">
<i class="fa fa-calendar-check-o" rel="tooltip" data-placement="right" title="Find resources, events, and announcements"></i>
</a>
</li>
<!--<li class="nav-item">-->
<!--<a class="nav-link" data-toggle="tab" href="#messages" role="tablist">-->
<!--<i class="now-ui-icons sport_user-run"></i>-->
<!--</a>-->
<!--</li>-->
</ul>
</div>
</div>
<!-- Tab panes -->
<!--announcements-->
<div class="tab-content gallery">
<div class="tab-pane active" id="home" role="tabpanel">
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="row collections">
<div class="col-md-6">
    <%= render 'shared/announcements' %>
</div>
<div class="col-md-6">
    <!--<img src="../assets/img/bg8.jpg" alt="" class="img-raised">-->
    <!--<img src="../assets/img/bg7.jpg" alt="" class="img-raised">-->
</div>
</div>
</div>
</div>
</div>
<div class="tab-pane" id="profile" role="tabpanel">
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="row collections">
<div class="col-md-6">
    <% @user.subscriptions.each do |subscription| %>
    <% if subscription.lost? && subscription.user == current_user %>
    <%= link_to subscription do %>
    <i class="fa fa-info-circle pet_profile" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Visit this Pets profile."></i>
    <% end %>
    <h6 class="pet_name"><%= subscription.title %></h6>
    <div class="actions">
        <%= link_to edit_subscription_path(subscription) do %>
        <i class="fa fa-pencil"></i>
        <% end %>
    </div>
    <%= image_tag(subscription.pet_image, class: "img-raised img-thumbnail lost")%>

    <%= link_to 'Report Found', subscriptions_found_path(subscription.id), class: "btn btn-outline btn-xl", id: "report_found" %>

    <% elsif subscription.user == current_user %>
    <h6 class="pet_name"><%= subscription.title %></h6>
        <div class="actions">
        <%= link_to edit_subscription_path(subscription) do %>
        <i class="fa fa-pencil"></i>
        <% end %>
    </div>
    <%= image_tag(subscription.pet_image, class: "img-raised img-thumbnail")%>
    <%= link_to 'Report Lost', subscriptions_lost_path(subscription.id), class: "btn btn-outline btn-xl", id: "report_lost", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', :title => 'Have you checked everywhere? Even checked with the neighbors?' %>
    <% elsif subscription.lost? %>
    <h6 class="pet_name"><%= subscription.title %> is missing!</h6>
    <%= link_to image_tag(subscription.pet_image, class: "img-raised img-thumbnail"), subscription %>
    <% else %>
    <h6 class="pet_name"><%= subscription.title %></h6>
    <%= image_tag(subscription.pet_image, class: "img-raised img-thumbnail")%>
    <% end %>
    <% end %>
</div>
<div class="col-md-6">
    <!--<img src="../assets/img/bg7.jpg" alt="" class="img-raised">-->
    <!--<img src="../assets/img/bg8.jpg" alt="" class="img-raised">-->
</div>
</div>
</div>
</div>
</div>
<div class="tab-pane" id="messages" role="tabpanel">
<div class="row">
<div class="col-md-10 offset-md-1">
<div class="row collections">
<div class="col-md-6">
    <!--<img src="../assets/img/bg3.jpg" alt="" class="img-raised">-->
    <!--<img src="../assets/img/bg8.jpg" alt="" class="img-raised">-->
</div>
<div class="col-md-6">
    <!--<img src="../assets/img/bg7.jpg" alt="" class="img-raised">-->
    <!--<img src="../assets/img/bg6.jpg" class="img-raised">-->
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>


</div>
</body>

</html>