config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs
  resources :subads, :path => 'announcements'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscriptions, :path => 'pets' 
  root 'home#index'
  mount Thredded::Engine => '/forum'
  resource :messageboard, path: 'messageboards', only: [:new]
  get '/private-topics/new' => 'thredded/private_topics#new', :as => :new_private_topic
  
  
  devise_for :users, 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'edit'}, 
  :controllers => { 
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"}

  get 'users/:id' => 'users#show', :as => :user_profile
  get 'persons/:id/profile' => 'persons#show', :as => :persons_profile
  get 'home/about', :path => 'about'
  get 'home/donate', :path => 'donate'
  get 'home/faq', :path => 'faq'
  get 'subscriptions/:id/lost' => "subscriptions#lost", :as => :subscriptions_lost
  get 'subscriptions/:id/found' => "subscriptions#found", :as => :subscriptions_found
  get 'subscriptions/lost_pets' => "subscriptions#lost_pets", :as => :lost_pets, :path => 'lost/pets'

  get 'persons/edit'

end

app/views/shared/_announcements.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Where's Hara | Lost Pets</title>
<style>
.profile-page .collections img {
margin-bottom: 30px;
height: 200px;
width: 700px;
}
.date{
display: inline-block; 
padding: 1em 0;
width: 130px;
background-color: white;
border: 1px solid #e6e7e9;
border-radius: 3em;
font-weight: 700;
font-size: 10px;
text-align: center;
z-index: 2;
position: relative;
margin : 1em 0 2em 0;
color: #34324b;
}


</style>
<ul id="timeline">


<li class="date" data-placement="right" data-toggle="tooltip" title="Today's Date. Just a reminder!"><%= Date.today.strftime("%B %d %Y") %></li>

<!--start list-->
<li>  <span class="job_title"><a href="/forum" target="blank" class="job_title">Visit the</a></span>
  <span class="job_info">community board</span></li>
<% @subads.each do |subad| %>
<li class="listing clearfix">

<div class="info">
  <span class="job_title"><%= link_to subad.title, subad, target: "_blank", class: "job_title" %></span>
  <span class="job_info"><%= subad.brand %> 
  <!--San Francisco <span>&bull;</span> March 1st</span>-->
</div>
<!--<span class="job_type freelance">Freelance</span>-->
<!--link_to subad do %>-->
<!--<i class="fa fa-arrow-circle-right" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="See More!"></i>-->
<!-- end %>-->

</li>
<% end %>
<!--end-->
<!--<li class="date"><a href="#"></li>-->

</ul>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/shared/_mobile.html.erb
<div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">
<ul class="navbar-nav navbar-logo navbar-switch">

</ul>
<ul class="navbar-nav">
<li class="nav-item">
<!--<a class="nav-link" href="../index.html">Back to Kit</a>-->
</li>
<li class="nav-item">
<!--<a class="nav-link" href="https://github.com/creativetimofficial/now-ui-kit/issues">Have an issue?</a>-->
</li>
<li class="nav-item">
<a class="nav-link twitter-sharrre-nav sharrre" rel="tooltip" title="" data-placement="bottom" href="#pablo" data-original-title="Tweet">
  <i class="fa fa-twitter"></i>
  <p class="hidden-lg-up">Twitter</p>
</a>
</li>
<li class="nav-item">
<a class="nav-link facebook-sharrre-nav sharrre" rel="tooltip" title="" data-placement="bottom" href="#pablo" data-original-title="Share">
  <% if current_user %>
  <!--<i class="fa fa-facebook-square"></i>-->
  <p class="hidden-lg-up"><li class="dropdown-item"><%= link_to "Logout", destroy_user_session_path, class: "", style: "", method: :delete %></li></p>
</a>
</li>
<li class="dropdown-item" id=""><%= link_to "Lost Pets Board", lost_pets_path %></li>
<li class="dropdown-item" id=""><%= link_to "Community Board", thredded_path %></li>

<% else %>
<li class="dropdown-item" id=""><%= link_to "Lost Pets Board", lost_pets_path %></li>
<li class="dropdown-item" id=""><%= link_to "Community Board", thredded_path %></li>
<div class="dropdown-divider"></div>
<li class="dropdown-item" id=""><%= link_to "Sign in with Facebook", "users/auth/facebook", id: "sign_in" %></li></div>
<% end %>
</ul>
</div>

app/views/shared/_navbar.html.1.erb
<style>
#dropdownMenu1{
background:transparent;
}

li a{
color: #131212;
font-size: 16px;
letter-spacing: 1.5px;
padding-left: 17px;
font-weight: 700;
opacity: 0.9;
}
a:hover {
color: #607D8B;
text-decoration: none; 
}
li{
text-decoration: none;
background-color: transparent;
-webkit-text-decoration-skip: objects;
font-size: 20px;
text-transform: uppercase;
font-weight: 300;
font-family: sans-serif;
float: initial;
}

#sign_in{
font-size: 13px;
padding-left: 5px;
}
.btn.focus, .btn:focus{
outline:none;
box-shadow:none;
}

.dropdown-menu{
border:none;
min-width: 13rem;
}

#fbook-img{
border-radius:50%;
width: 90px;
}


</style>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <%= link_to image_tag("w-logo.png", class: "navbar"), root_path %>
    </div>

    <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
  <div id="fbook-div">
    <% if current_person %>
    Welcome <strong><%= current_person.name %></strong>!
    <% else %>
    Toggle Menu
  <% end %>
  </div>
    <span class="caret"></span>
  </button>
<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  <% if current_person %>
  <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
  <strong><li><%= link_to "View Profile", persons_profile_url(current_person) %></li></strong>
  <% else %>
  <li id="sign_in"><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
  <% end %>
</ul>
</div>
 
  </div> <!-- Subscriptions Model == Pets -->
  <%= link_to 'Just Lost My Pet!', new_subscription_path, class: "btn btn-outline btn-xl", 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => 'Post a Lost Pet' %>
</nav>

<!--tooltips-->
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/shared/_navbar.html.erb
<style>
.bg-primary {
background-color: rgba(207, 216, 220, 0.38) !important;
}
.dropdown-menu {
background-color:rgb(58, 183, 126);
}
#user_name{
padding-left: 10px;
letter-spacing: 2px;
text-transform: uppercase;
color: white;
font-size: smaller;
text-decoration: none;
}
</style>
<nav class="navbar navbar-toggleable-md bg-primary fixed-top navbar-transparent" color-on-scroll="500">
  <a class="navbar-brand" href="/">
    <img src="http://www.lavail.io/wp-content/uploads/2017/09/whereshara-web-logo.png" width="70" height="70" position:absolute; alt="">
  </a>
<div class="container">

<div class="navbar-translate">
<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-bar bar1"></span>
<span class="navbar-toggler-bar bar2"></span>
<span class="navbar-toggler-bar bar3"></span>
</button>

<% if current_user %>
 <%= link_to current_user.name, user_profile_url(current_user), id: "user_name", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', :title => 'Click to go to your profile' %>
<% else %>

<% end %>

</div>

<div class="dropdown button-dropdown">
<a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
<span class="button-bar"></span>
<span class="button-bar"></span>
<span class="button-bar"></span>
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-header" style="color:white;">  </a>
<% if current_user %>
<li class="dropdown-item"><%= link_to "Logout", destroy_user_session_path, class: "", style: "", method: :delete %></li>

<li class="dropdown-item"><%= link_to "Account", edit_user_registration_path %></li>
<% else %>
<li class="dropdown-item" id="sign_in"><%= link_to "Sign in", "users/auth/facebook", id: "sign_in" %></li>
<% end %>
<div class="dropdown-divider"></div>
<li class="dropdown-item" id=""><%= link_to "Lost Pets Board", lost_pets_path %></li>
<li class="dropdown-item" id=""><%= link_to "Community Board", thredded_path %></li>
<div class="dropdown-divider"></div>
<li class="dropdown-item" id=""><%= link_to "Add Pet", new_subscription_path %></li></div>
</div>
<!--mobile menu-->
<%= render 'shared/mobile' %>
<!--mobile menu end-->

</div>
</nav>