config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs
  resources :subads, :path => 'announcements'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscriptions, :path => 'pets' 
  root 'home#index'
  mount Thredded::Engine => '/forum'
  resource :messageboard, path: 'messageboards', only: [:new]
  get '/private-topics/new' => 'thredded/private_topics#new', :as => :new_private_topic
  
  
  devise_for :users, 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'edit'}, 
  :controllers => { 
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"}

  get 'users/:id' => 'users#show', :as => :user_profile
  get 'persons/:id/profile' => 'persons#show', :as => :persons_profile
  get 'home/about', :path => 'about'
  get 'home/donate', :path => 'donate'
  get 'home/faq', :path => 'faq'
  get 'subscriptions/:id/lost' => "subscriptions#lost", :as => :subscriptions_lost
  get 'subscriptions/:id/found' => "subscriptions#found", :as => :subscriptions_found
  get 'subscriptions/lost_pets' => "subscriptions#lost_pets", :as => :lost_pets, :path => 'lost/pets'

  get 'persons/edit'

end

app/models/subscription.rb
# Subscriptions Model == Pets. This is because I cloned this workspace from another one of my projects. I think i'll rename the models for less confusion later, but since the project is small we'll keep it this way.

class Subscription < ActiveRecord::Base
  require 'twilio-ruby'
  
  # Callback for lost pet
  extend ActiveModel::Callbacks
  
  #define_model_callbacks :lost, :found, :only => [:after]

  #after_lost  :notify_owner
  #after_found :mark_found
  
  #end
  belongs_to :user

  #after_found :reminder
  
  
  #after_create :lost
  
  #scope for lost method in controller
  #scope :is_lost, ->{ where(lost: true) }

 # End

 # Notify our appointment attendee X minutes before the appointment time
  
  
  def reminder
  end


  #def when_to_run
  #   minutes_before_appointment = 1.minutes
  #   time - minutes_before_appointment
  # end


  	handle_asynchronously :reminder,  :priority => 0
  	
  	
  # Mark the pet as lost
  # def lost
  #   run_callbacks :lost :found do
  #     puts "Marking Pet lost..."
  #   end
  # end
  
  private


  def self.found
    @twilio_number = '+12065391879'
		@client = Twilio::REST::Client.new 'AC4e9ac55e2bbd7fc3a434e3d37896782e','5934a63e2b41eddfaa0275f20b328db9'
    time_str = ((self.time).localtime).strftime("%I:%M%p on %b. %d, %Y")
    reminder = "Hi Great news! #{self.title} was located. Please check your email and social media for any messages."
    @client.messages.create(
      :from => @twilio_number,
      :to => self.phone_number,
      :body => reminder,
    )
  end
  

  # end mark pet as lasted
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
# include ApplicationHelper
# require 'subscription.rb'
before_action :set_subscription, only: [:show, :edit, :update, :destroy]
before_action :correct_user, only: [:edit, :update, :destroy]
# GET /subscriptions
# GET /subscriptions.json
def index
end

# GET /subscriptions/1
# GET /subscriptions/1.json
def show
end

# GET /subscriptions/new
def new
  # check if user has two subscriptions or less
  if current_user.subscriptions.size <= 2
  # if the user has less than 2 subscriptions, we'll allow them to create a 3rd
  @subscription = current_user.subscriptions.build
  # but if the user aleady has three subscriptions, then we redirect them with a message
  elsif current_user.subscriptions.size >= 3
  redirect_to user_profile_url(current_user.id), notice: 'You can only have 3 pets for now.'
  end
end

# GET /subscriptions/1/edit
def edit
end

# POST /subscriptions
# POST /subscriptions.json
def create
@subscription = current_user.subscriptions.build(subscription_params)

respond_to do |format|
  if @subscription.save

    format.html { redirect_to user_profile_url(current_user.id), notice: 'Pet was successfully created.' }
    format.json { render :show, status: :created, location: @subscription }
  else
    format.html { render :new }
    format.json { render json: @subscription.errors, status: :unprocessable_entity }
  end
end
end

# PATCH/PUT /subscriptions/1
# PATCH/PUT /subscriptions/1.json
def update
respond_to do |format|
  if @subscription.update(subscription_params)
    format.html { redirect_to user_profile_url(current_user.id), notice: 'Pet was successfully updated.' }
    format.json { render :show, status: :ok, location: @subscription }
  else
    format.html { render :edit }
    format.json { render json: @subscription.errors, status: :unprocessable_entity }
  end
end
end

# DELETE /subscriptions/1
# DELETE /subscriptions/1.json
def destroy
@subscription.destroy
respond_to do |format|
  format.html { redirect_to :back, notice: 'Pet was successfully destroyed.' }
  format.json { head :no_content }
end
end

# custom methods
# implementing a sms notification on method in v2
def lost
  #find each pet owned by the user
  @subscriptions = current_user.subscriptions.find_by(id: params[:id])
  #once located, update the pet by its id
  @subscriptions.update(lost: true)
  #after updating the column route back to user profile
  redirect_to lost_pets_url, notice: "Your Pet was reported Lost and added to the Lost pet Board."
end
# implementing a sms notification on method in v2
def found
  @users = User.all
  #find each pet owned by the user
  @subscriptions = current_user.subscriptions.find_by(id: params[:id])
  # Sends email to user when after pet is marked foun.
 # NotificationMailer.notification_email(@subscriptions.url).deliver
  #once located, update the pet by its id
  @subscriptions.update(lost: false)
  #after updating the column route back to pet board
  redirect_to lost_pets_url, notice: "This Pet has been marked found. Congratulations!"
end

def lost_pets
  @subscription = Subscription.all
  # @subscriptions = Subscription.where(lost: true).is_lost
end
# end 

private
# Use callbacks to share common setup or constraints between actions.
def set_subscription
  @subscription = Subscription.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def subscription_params
   params.require(:subscription).permit(:id, :title, :company, :url, :start_time, :end_time, :phone_number, :time, :animal, :pet_image, :option_1, :option_2, :gender, :breed, :notes)
end

def correct_user
  @subscriptions = current_user.subscriptions.find_by(id: params[:id])
  redirect_to user_profile_url, notice: "Not authorized to edit this person" if @subscription.nil?
end



end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
a {
color: #a0dbf9;
}
.time-control{
display:none;
}

select {
text-transform: none;
color: #c12d4d;
font-size: 16px;
font-weight: 800;
}

input#subscription_phone_number{
color: #a93466;
font-weight: 700;
margin-left: -5%;
}

input#subscription_url{
color: #a93466;
font-weight: 700;
}

label{
text-transform: uppercase;
}

/* iphone 6 Portrait */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait) { 
form {
width:70%;
margin-left: 10%;
  }
}

@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait) { 
.btn-primary {
/*margin-left: -50%;*/
  }
}
</style>
<%= form_for(@subscription) do |f| %>
<% if @subscription.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

  <ul>
  <% @subscription.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

<!--Pet specific info-->
<div class="form-group">
    <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="As it appears on the collar."></i>
<%= f.label :Pets_name %><br>
<%= f.text_field :title, placeholder: 'Pets Name ', class: "form-control border-input", id: "pet_name" %> 
</div>
<br>

<div class="form-group">
<%= f.label :Help_us_identify_your_pet %><br>
<%= f.select(:gender, options_for_select([['Her'], ['Him']]), class: "company-select") %>
</div>


<br>
<div class="form-group">
    <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Dog, Cat, Reptile, Other."></i>
<%= f.label :type %><br>
<%= f.select(:animal, options_for_select([['Dog'], ['Cat'], ['Tarantula'], ['Other']]), class: "company-select") %>
</div>

<br>

<br>
<div class="form-group">
    <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Pitbull, Labrador Retriever, etc."></i>
<%= f.label :Breed %><br>
<%= f.text_field :breed, placeholder: 'Pet Breed ', class: "form-control border-input", id: "pet_name" %> 
</div>

<br>
<div class="form-group">
    <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Keep this short and sweet, but be descriptive as possible."></i>
<%= f.label :Notes %><br>
<%= f.text_area :notes, placeholder: 'Last seen outside of QFC on Broadway in Capitol Hill. She has on a red collar and about is about 12 pounds. ', class: "form-control border-input", id: "pet_name" %> 
</div>

<br>
<i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Optional"></i>
<%= f.label :Pet_image %><br>
<%= f.text_field :pet_image, placeholder: 'http://somewebsite.com/petimage.png', class: "form-control border-input", id: "pet_image" %>
</div>
<!--end-->
<br>
<br>
<div class="form-group">
<%= f.label :Select_a_neighborhood %><br>
    <p id="tags_p">Don't see your Neighborhood or Area? Let us know and We'll add it.  <%= mail_to "nance.aris@gmail.com", "Here", bcc: "nance.aris@gmail.com",
subject: "Add a Neighborhood or Area", body: "Please include the Neighborhood name or the Area name." %>
</p>
    <br>
<%= f.select(:company, options_for_select([['First Hill'], ['Pioneer Square'], ['Capitol Hill'], ['Madison Park'], ['Madison Valley'], ['Central District'], ['Downtown'], ['Belltown'], ['Southeast Seattle'], ['Queen Anne'], ['Leschi'], ['West Seattle'], ['Georgetown'], ['Sodo'],['Columbia City'], ['Mt. Baker'], ['Lakewood'], ['Ballard'], ['Fremont'], ['Magnolia'], ['Wallingford'], ['University District'], ['Greenlake'], ['Greenwood'], ['Roosevelt'], ['Lake City'], ['International District'], ['Other']  ]), class: "company-select") %>
</div>

<div class="form-group">
<!--f.datetime_select :start_time, class: "form-control border-input" %>-->
 <!--time_select :subscription, :time, {:class => "form-control time-control" } %>-->
</div>

<!--<div class="form-group">-->
<!-- f.label :When_does_your_subscription_end_? %><br>-->
 <!--f.datetime_select :end_time, class: "form-control border-input" %>-->
<!-- date_select :subscription, :time, {:class => "form-control" } %>-->
<!--</div>-->

<br>
<br>

<br>


<br>
<div class="actions">
<%= f.submit 'submit', class: "btn btn-outline btn-xl" %>
</div>
<br>
<br>

<% end %>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/subscriptions/edit.html.erb
<title>Where's Hara | Edit Pet</title>
<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Where's Hara | Lost Pets</title>
<style>
.clearfix:before, .clearfix:after {
	content:" ";
	display: table;

}
.clearfix:after{
	clear: both;
}
.wrapper{
	width:750px;
	max-width: 90%;
	margin: 0 auto;
}
.main_header{
	margin: 5em 0 3em 0;
}
.logo img {
	
		width:75px;
		float: left;
}
.logo h1{
	float: left;
	margin: 0 0 0 1em;
	text-transform: uppercase;
	font-size: 1.34em;
	padding-top: 1.8em;
	color :#34324b;
}
.logo h1 span{
	font-weight: 400;
}
.nav{
	float:right;
	padding-top: 2.7em;
}
.nav a {
	color: #74718f;
	margin-left: 1em;
	text-decoration: none;
	font-weight: 550;
}
.current{
	color: #34324b;
	font-weight: 700;
	
}
#timeline{
  width: 60%;
  position: relative;
  list-style: none;
  padding: 0;
  margin-left: 15%;
  margin-top: 5%;

}
#timeline a {
text-decoration: none;

}
 #timeline:after {
    content: "";
    width: 1px;
    /*background: 1px #e6e7e9;*/
    height: 90%;
    position: absolute;
    top: 3em;
    left: 3em;
    z-index: 0; }
#timeline .listing{
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 0.3em;
  padding: 1em;
  margin-bottom: 1em;
  position: relative;
  display: table;
  width: 100%;
  transition: all .3s ease-in-out;


}
.listing:hover{
  cursor: pointer;
  box-shadow: 0px 2px 40px 0 rgba(0,0,0,0.1);

}
#timeline .listing img,.info,.job_type{
  display: table-cell;
  vertical-align: middle;
  font-size: 0.9em;
  color: #74718f;

}
#timeline .image_wrapper{
  width: 60px;
}
#timeline .image_wrapper img{
  width: 60px;
  display : block;
  margin : 0 auto;
  border-radius: 0.25em;
}
.info{
  line-height: 1.25;
  width: 640px;
  padding-left: 25px;
}
.job_title{
  font-weight: 700;
  font-size: 1.5em;
  color: #34324b;
  padding-left: 0px;
}
.job_info{
  color:#74718f;
  display: block;

}
.job_info span{
  margin: 0 .75em;
}
.job_type{
  text-transform: uppercase;
  font-weight: 700;
  font-size: 0.75em;
  position: relative;
  white-space: nowrap;
  padding-top: .6em;
  width: 100px;
}
.job_type:before{
  content: " ";
  background-color: #fd7576;
  width:10px;
  height: 10px;
  border-radius: 100%;
  position: absolute;
  left:-20px;
  top:27px;
}
.full_time{
  color: #fd7576;

}
.full_time:before{
background-color:#fd7576;
}
.part_time{
  color: #fec85d;

}
.part_time:before{
background-color:#fec85d;
}
.freelance{
  color: #4db8de;

}
.freelance:before{
background-color:#4db8de;
}
.contract{
  color: #a378fc;

}
.contract:before{
background-color:#a378fc;
}
.date{
  display: inline-block; 
  padding: 1em 0;
  width: 100px;
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 3em;
  font-weight: 700;
  font-size: 10px;
  text-align: center;
  z-index: 2;
  position: relative;
  margin : 1em 0 2em 0;
  color: #34324b;
}
.load_more{
  text-align: center;

}
.button{
  border : 2px solid #a378fc;
  outline: none;
  padding: 1em 3.5em;
  text-align: center;
  background: transparent;
  border-radius: 3em;
  color: #a378fc;
  transition:all .3s ease-in-out;
}
.button:hover{
 background-color: #a378fc;
  color: white;

}
@media only screen and (max-width: 768px){
  .main_header{
  margin: 3em 0;
}
.logo{
   display: block;
  text-align: center;
}
.logo img {
  
    float: none;

}
.logo h1{
  float: none;
  margin: 0 auto;
  text-transform: uppercase;
  font-size: 1.1em;
}

#timeline a {
padding-left: 1px !important;
}

/* iphone 6 Portrait */
/* Portrait and Landscape */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) {
.job_title {
font-size:20px;
  }
}
</style>
<ul id="timeline">


<li class="date" data-placement="right" data-toggle="tooltip" title="Today's Date. Just a reminder!"><%= Date.today.strftime("%B %d %Y") %></li>

<!--start list-->
<% @subscription.each do |subscription| %>
<li class="listing clearfix">
<div class="image_wrapper">
<%= image_tag(subscription.pet_image) %>
</div>
<div class="info">
  <span class="job_title"><%= link_to subscription.title, subscription, class: "job_title" %></span>
  <span class="job_info"><%= subscription.breed %> 
  <!--San Francisco <span>&bull;</span> March 1st</span>-->
</div>
<!--<span class="job_type freelance">Freelance</span>-->
<!--link_to subscription do %>-->
<!--<i class="fa fa-arrow-circle-right" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="See More!"></i>-->
<!-- end %>-->

</li>
<% end %>
<!--end-->
<!--<li class="date"><a href="#"></li>-->

</ul>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/subscriptions/lost_pets.html.1.erb
<!DOCTYPE html>
<html>
<title>Where's Hara | Lost Pets</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
/* Portrait and Landscape */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) { 
.btn-xl {
/*margin-top: -30%;*/
/*position: absolute;*/
/*margin-left: 20%;*/
display:none !important;
}
}
.img-raised{
width: 300px;
height: 300px;
}
.w3-blue-grey{
background: linear-gradient(to left,#26A69A,#81C784); !important;
}
.w3-light-grey{
color:#fff !important;
background: linear-gradient(to left,rgb(250, 250, 250),#81C784)
}
</style>
<body>

<!-- First Grid:Lost Pets -->
<div class="w3-row">
  <div class="w3-half w3-light-grey w3-center" style="height:1000px">
    <div class="w3-padding-64">
      <h2 style="font-size: 50px;
    font-weight: 600;
    text-transform: uppercase;
    color: #fafafa;letter-spacing: 10px;">Lost Pets</h2>
      <p>Welcome to Where's Hara. Please look closely at the Pets listed below. Maybe you've seen then around?.</p>
    </div>
    <div class="w3-row lost_pets">
      <% @subscription.each do |subscription| %>
      <% if subscription.lost? %>
      <div class="w3-half">
      <%= link_to image_tag(subscription.pet_image, class: "img-raised img-thumbnail"), subscription %>
      <br>
      <span class="lost_at" data-toggle = 'tooltip', data-placement = 'right', title = 'Missing since...'><%= subscription.created_at.strftime("%B %d %Y") %></span>
      <%= link_to 'Report Found', subscriptions_found_path(subscription.id), class: "btn btn-outline btn-xl", id: "report_found", 'data-toggle' => 'tooltip', 'data-placement' => 'top', :title => 'You certify you found this Pet and its safe?' %>
      </div>
      <% else %>
      
      <% end %>
    <!--end lost pets-->
      <% end %>
    </div>
   
    <br>
  </div>
  <div class="w3-half w3-blue-grey w3-container" style="height: 1000px">
    <div class="w3-padding-64 w3-center">
      <h1 style="font-size: 50px;
    font-weight: 600;
    text-transform: uppercase;
    color: #fafafa;letter-spacing: 10px;"> </h1>
      <img src="img_avatar3.png" class="w3-margin w3-circle" alt="Person" style="width:50%">
      <div class="w3-left-align w3-padding-large">
        <p>Lorem ipusm sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      </div>
    </div>
  </div>
</div>

<!-- Second Grid: Swing By & Contact -->
<!--<div class="w3-row">-->
<!--  <div class="w3-half w3-dark-grey w3-container w3-center" style="height:600px">-->
<!--    <div class="w3-padding-64">-->
<!--      <h1>Swing By</h1>-->
<!--    </div>-->
<!--    <div class="w3-padding-64">-->
<!--      <p>..for a cup of coffee, or whatever.</p>-->
<!--      <p>Chicago, US</p>-->
<!--      <p>+00 1515151515</p>-->
<!--      <p>test@test.com</p>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="w3-half w3-teal w3-container" style="height:600px">-->
<!--    <div class="w3-padding-64 w3-padding-large w3-center">-->
<!--      <h1>Contact</h1>-->
<!--      <p class="w3-opacity">GET IN TOUCH</p>-->
<!--      <form class="w3-container w3-card-2 w3-padding-32 w3-white">-->
<!--        <div class="w3-section">-->
<!--          <label>Name</label>-->
<!--          <input class="w3-input" style="width:100%;" type="text" required>-->
<!--        </div>-->
<!--        <div class="w3-section">-->
<!--          <label>Name</label>-->
<!--          <input class="w3-input" style="width:100%;" type="text" required>-->
<!--        </div>-->
<!--        <div class="w3-section">-->
<!--          <label>Subject</label>-->
<!--          <input class="w3-input" style="width:100%;" type="text" required>-->
<!--        </div>-->
<!--        <button type="button" class="w3-btn">Send</button>-->
<!--      </form>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

</body>
</html> 

app/views/subscriptions/lost_pets.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<title>Where's Hara | Lost Pets</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Where's Hara is an online platform focused on connecting the pet community and helping lost pets get home.">
<meta name="keywords" content="lost pets, lost pets in seattle, seattle lost dogs, adopt pets, adopt animals, find lost pets, lost dog, lost cat">
<meta name="author" content="">

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


<!-- Plugin CSS -->
<link rel="stylesheet" href="device-mockups/device-mockups.min.css">

<!-- Custom styles for this template -->
<link href="css/new-age.min.css" rel="stylesheet">

<style>
#contact: {
display:none;
}
body{
background: linear-gradient(to left,#26A69A,#81C784);
}
.img-thumbnail{
width: 45%;
}
section.cta .cta-content h2{
margin-top: -10%;
}
.modal-backdrop {
position: fixed;
top: 0;
right: 0;
bottom: 0;
left: 0;
 z-index: 0; 
background-color: #000;
}
.modal.show .modal-dialog {
-webkit-transform: translate(0,0);
transform: translate(0,0);
margin-top: 15%;
}
#pet_name{
color: white;
font-weight: 700;
letter-spacing: 3px;
margin-top: -10%;
margin-left: 5%;
text-transform:uppercase;
}
footer{
margin-top: 20%;
}
/*mac laptop*/
@media screen and (min-device-width: 1200px) and (max-device-width: 1600px) {
  section.cta .cta-content h2{
  margin-left:1%;
  }
}
/*iphone 6*/
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
section.cta .cta-content h2{
margin-left: 1%;
margin-top: -40%;
  }
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
.img-thumbnail {
width: 100%;
}
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
#pet_name {
margin-top:0px;
}
}
</style>
</head>

<body id="page-top">



<section class="cta">
<div class="cta-content">
<div class="container">
<h2>Seen us around?</h2>

  <div class="row justify-content-start">
    <% @subscription.each do |subscription| %>
    <% if subscription.lost? %>
    <div class="col-4">
      <%= link_to image_tag(subscription.pet_image, class: "img-raised img-thumbnail", 'data-toggle' => 'tooltip', 'data-placement' => 'top', :title => 'View the Pets profile'), subscription %>
      <p id="pet_name"><%= subscription.title %></p>
    </div>
    <% end %>
  <% end %>
</div>

</div>

</section>



<!-- Bootstrap core JavaScript -->


<!-- Plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->


</body>

</html>

app/views/subscriptions/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Where's Hara | <%= @subscription.title %></title>
<style>
body{
background:linear-gradient(to left,#26A69A,#81C784);
}
.row{
margin-top: 5%;
}
#show_image{
width: 15%;
}
.alert{
z-index:2;
}
.lead{
font-size: 2.25rem;
font-weight: 100;
color: white;
}
.mt-5 {
margin-top: 3rem!important;
text-transform: capitalize;
color: azure;
}
.card{
border:none;
}
.text-center{
margin-top: 5%;
}
footer{
margin-top:20%;
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
.text-center{
margin-top: 30%;
}
}
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait){
#show_image {
width: 60%;
}
}

/* iphone 6 Portrait */
/* Portrait and Landscape */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) {
#menu-toggle {
 display:none !important;
  }
}

  </style>
<!-- Page Content -->
<div class="container">
<div class="row">
<div class="col-lg-12 text-center">
     <%= image_tag(@subscription.pet_image, id: "show_image", class: "img-thumbnail") %>
     <br>
     <br>
     <!--share on twitter-->
     <%= link_to "http://twitter.com/home?status= Our #{@subscription.animal} is missing. #{@subscription.title} is a friendly #{@subscription.breed} and was last seen in #{@subscription.company}. If see #{@subscription.gender} report it here #{subscription_url(@subscription)}", target: "_blank" do %><i style="font-size: 27px; color: #ffffff;" class="fa fa-twitter" data-placement="right" data-toggle="tooltip" title="Share me on Twitter!"></i><% end %>
     <!--end-->
  <h1 class="mt-5"><%= @subscription.title %> the <%= @subscription.breed %></h1>
  <p class="lead"><%= @subscription.notes %></p>
  <ul class="list-unstyled">
    <li></li>
    <!--<li> link_to 'Report Found', lost_pets_path, target: "_blank", class: "btn btn-outline btn-xl", 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => 'Report only if you believe you located the Pet!' %>-->
    <li><%= link_to 'Owner Profile', user_profile_path(@subscription.user), target: "_blank", class: "btn btn-outline btn-xl" %>
    </li>
  </ul>
  
  <h1 class="mt-5"><span style="font-size:20px; font-weight:100;">Last seen in </span><%= @subscription.company %></h1>
</div>
</div>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>



<!-- link_to 'Edit', edit_subad_path(@subscription) %> |-->
<!--link_to 'Back', subads_path %>-->