config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs
  resources :subads, :path => 'announcements'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :subscriptions, :path => 'pets' 
  root 'home#index'
  mount Thredded::Engine => '/forum'
  resource :messageboard, path: 'messageboards', only: [:new]
  get '/private-topics/new' => 'thredded/private_topics#new', :as => :new_private_topic
  
  
  devise_for :users, 
  :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'edit'}, 
  :controllers => { 
    :registrations => "users/registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"}

  get 'users/:id' => 'users#show', :as => :user_profile
  get 'persons/:id/profile' => 'persons#show', :as => :persons_profile
  get 'home/about', :path => 'about'
  get 'home/donate', :path => 'donate'
  get 'home/faq', :path => 'faq'
  get 'subscriptions/:id/lost' => "subscriptions#lost", :as => :subscriptions_lost
  get 'subscriptions/:id/found' => "subscriptions#found", :as => :subscriptions_found
  get 'subscriptions/lost_pets' => "subscriptions#lost_pets", :as => :lost_pets, :path => 'lost/pets'

  get 'persons/edit'

end

app/models/subad.rb
class Subad < ActiveRecord::Base
    def to_param
        "#{id} #{title}".parameterize
    end
end

app/controllers/subads_controller.rb
class SubadsController < ApplicationController
  before_action :set_subad, only: [:show, :edit, :update, :destroy]


  # GET /subads
  # GET /subads.json
  def index
    @subads = Subad.all
  end

  # GET /subads/1
  # GET /subads/1.json
  def show
  end

  # GET /subads/new
  def new
    if current_person.admin == true 
    @subad = Subad.new
  else
    redirect_to root_path, notice: 'Sorry, not authorized to add a Freebie :-).'
    end
  end

  # GET /subads/1/edit
  def edit
  end

  # POST /subads
  # POST /subads.json
  def create
    @subad = Subad.new(subad_params)

    respond_to do |format|
      if @subad.save
        format.html { redirect_to @subad, notice: 'Subad was successfully created.' }
        format.json { render :show, status: :created, location: @subad }
      else
        format.html { render :new }
        format.json { render json: @subad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subads/1
  # PATCH/PUT /subads/1.json
  def update
    respond_to do |format|
      if @subad.update(subad_params)
        format.html { redirect_to @subad, notice: 'Subad was successfully updated.' }
        format.json { render :show, status: :ok, location: @subad }
      else
        format.html { render :edit }
        format.json { render json: @subad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subads/1
  # DELETE /subads/1.json
  def destroy
    @subad.destroy
    respond_to do |format|
      format.html { redirect_to subads_url, notice: 'Subad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subad
      @subad = Subad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subad_params
      params.require(:subad).permit(:title, :image, :url, :content, :brand)
    end
end

app/helpers/subads_helper.rb
module SubadsHelper
end

app/views/subads/_form.html.erb
<%= form_for(@subad) do |f| %>
  <% if @subad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subad.errors.count, "error") %> prohibited this subad from being saved:</h2>

      <ul>
      <% @subad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :Name_this_subscription %>
  <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Try to be Creative! Remeber, Users will see this first."></i>
  <%= f.text_field :title, placeholder: '45 Days Free', class: "form-control border-input" %>
  </div>
  <br>
  <br>
  <div class="form-group">
  <%= f.label :Descrition %>
  <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="Keep it short and sweet!"></i>
  <%= f.text_area :content, placeholder: 'Short Descrition', class: "form-control border-input" %>
  </div>
  <br>
  <br>
  <div class="form-group">
  <%= f.label :Brand_or_Company_name %>
 
  <%= f.text_field :brand, placeholder: 'Hulu, Netflix, Apple, etc.', class: "form-control border-input" %>
  </div>
  <br>
  <br>
  <div class="form-group">
  <%= f.label :Image_or_logo %>
  <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="The image should be a URL and Transparent if able."></i>
  <%= f.text_field :image, placeholder: 'https://yourimage.com/image.png', class: "form-control border-input" %>
  </div>
  <br>
  <br>
  <div class="form-group">
  <%= f.label :Subscription_url %>
  <i class="fa fa-info-circle" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="The URL where Users signup!"></i>
  <%= f.text_field :url, placeholder: 'Where does the User signup?', class: "form-control border-input" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/subads/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @subad %> |
<%= link_to 'Back', subads_path %>

app/views/subads/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Where's Hara | Lost Pets</title>
<style>
.clearfix:before, .clearfix:after {
	content:" ";
	display: table;

}
.clearfix:after{
	clear: both;
}
.wrapper{
	width:750px;
	max-width: 90%;
	margin: 0 auto;
}
.main_header{
	margin: 5em 0 3em 0;
}
.logo img {
	
		width:75px;
		float: left;
}
.logo h1{
	float: left;
	margin: 0 0 0 1em;
	text-transform: uppercase;
	font-size: 1.34em;
	padding-top: 1.8em;
	color :#34324b;
}
.logo h1 span{
	font-weight: 400;
}
.nav{
	float:right;
	padding-top: 2.7em;
}
.nav a {
	color: #74718f;
	margin-left: 1em;
	text-decoration: none;
	font-weight: 550;
}
.current{
	color: #34324b;
	font-weight: 700;
	
}
#timeline{
  width: 60%;
  position: relative;
  list-style: none;
  padding: 0;
  margin-left: 15%;
  margin-top: 5%;

}
#timeline a {
text-decoration: none;

}
 #timeline:after {
    content: "";
    width: 1px;
    /*background: 1px #e6e7e9;*/
    height: 90%;
    position: absolute;
    top: 3em;
    left: 3em;
    z-index: 0; }
#timeline .listing{
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 0.3em;
  padding: 1em;
  margin-bottom: 1em;
  position: relative;
  display: table;
  width: 100%;
  transition: all .3s ease-in-out;


}
.listing:hover{
  cursor: pointer;
  box-shadow: 0px 2px 40px 0 rgba(0,0,0,0.1);

}
#timeline .listing img,.info,.job_type{
  display: table-cell;
  vertical-align: middle;
  font-size: 0.9em;
  color: #74718f;

}
#timeline .image_wrapper{
  width: 60px;
}
#timeline .image_wrapper img{
  width: 60px;
  display : block;
  margin : 0 auto;
  border-radius: 0.25em;
}
.info{
  line-height: 1.25;
  width: 640px;
  padding-left: 25px;
}
.job_title{
  font-weight: 700;
  font-size: 1.5em;
  color: #34324b;
  padding-left: 0px;
}
.job_info{
  color:#74718f;
  display: block;

}
.job_info span{
  margin: 0 .75em;
}
.job_type{
  text-transform: uppercase;
  font-weight: 700;
  font-size: 0.75em;
  position: relative;
  white-space: nowrap;
  padding-top: .6em;
  width: 100px;
}
.job_type:before{
  content: " ";
  background-color: #fd7576;
  width:10px;
  height: 10px;
  border-radius: 100%;
  position: absolute;
  left:-20px;
  top:27px;
}
.full_time{
  color: #fd7576;

}
.full_time:before{
background-color:#fd7576;
}
.part_time{
  color: #fec85d;

}
.part_time:before{
background-color:#fec85d;
}
.freelance{
  color: #4db8de;

}
.freelance:before{
background-color:#4db8de;
}
.contract{
  color: #a378fc;

}
.contract:before{
background-color:#a378fc;
}
.date{
  display: inline-block; 
  padding: 1em 0;
  width: 100px;
  background-color: white;
  border: 1px solid #e6e7e9;
  border-radius: 3em;
  font-weight: 700;
  font-size: 10px;
  text-align: center;
  z-index: 2;
  position: relative;
  margin : 1em 0 2em 0;
  color: #34324b;
}
.load_more{
  text-align: center;

}
.button{
  border : 2px solid #a378fc;
  outline: none;
  padding: 1em 3.5em;
  text-align: center;
  background: transparent;
  border-radius: 3em;
  color: #a378fc;
  transition:all .3s ease-in-out;
}
.button:hover{
 background-color: #a378fc;
  color: white;

}
@media only screen and (max-width: 768px){
  .main_header{
  margin: 3em 0;
}
.logo{
   display: block;
  text-align: center;
}
.logo img {
  
    float: none;

}
.logo h1{
  float: none;
  margin: 0 auto;
  text-transform: uppercase;
  font-size: 1.1em;
}

#timeline a {
padding-left: 1px !important;
}

/* iphone 6 Portrait */
/* Portrait and Landscape */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) {
.job_title {
font-size:20px;
  }
}
</style>
<ul id="timeline">


<li class="date" data-placement="right" data-toggle="tooltip" title="Today's Date. Just a reminder!"><%= Date.today.strftime("%B %d %Y") %></li>

<!--start list-->
<% @subads.each do |subad| %>
<li class="listing clearfix">
<div class="image_wrapper">
<%= image_tag(subad.image) %>
</div>
<div class="info">
  <span class="job_title"><%= link_to subad.title, subad, class: "job_title" %></span>
  <span class="job_info"><%= subad.brand %> 
  <!--San Francisco <span>&bull;</span> March 1st</span>-->
</div>
<!--<span class="job_type freelance">Freelance</span>-->
<!--link_to subad do %>-->
<!--<i class="fa fa-arrow-circle-right" aria-hidden="true" data-placement="right" data-toggle="tooltip" title="See More!"></i>-->
<!-- end %>-->

</li>
<% end %>
<!--end-->
<!--<li class="date"><a href="#"></li>-->

</ul>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/subads/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', subads_path %>

app/views/subads/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<style>
body{
background:linear-gradient(to left,#26A69A,#81C784);
}
#show_image{
width: 30%;
}
.alert{
z-index:2;
}
.lead{
font-size: 2.25rem;
font-weight: 100;
color: white;
}
.mt-5 {
margin-top: 3rem!important;
text-transform: capitalize;
color: azure;
}
.card{
border:none;
}
.text-center{
margin-top: 5%;
}
/* iphone 6 Portrait */
/* Portrait and Landscape */
@media only screen and (min-device-width: 375px) and (max-device-width: 667px) {
#menu-toggle {
 display:none !important;
  }
}

  </style>
<!-- Page Content -->
<div class="container">
<div class="row">
<div class="col-lg-12 text-center">
     <%= image_tag(@subad.image, id: "show_image") %>
     <!--share on twitter-->
     <%= link_to "http://twitter.com/home?status=Need something free in your life? Get #{@subad.title} from #{@subad.brand} #{subad_url(@subad)} Manage your Subscription here!", target: "_blank" do %><i style="font-size: 27px; color: #ffffff;" class="fa fa-twitter" data-placement="right" data-toggle="tooltip" title="Share this on Twitter!"></i><% end %>
     <!--end-->
  <h1 class="mt-5"><%= @subad.brand %></h1>
  <p class="lead"><%= @subad.content %></p>
  <ul class="list-unstyled">
    <li></li>
    <li><%= link_to 'Claim', @subad.url, target: "_blank", class: "btn btn-outline btn-xl" %></li>
  </ul>
</div>
</div>
</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>



<!-- link_to 'Edit', edit_subad_path(@subad) %> |-->
<!--link_to 'Back', subads_path %>-->